# Generated by Django 4.2.5 on 2023-09-13 10:11

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, validators=[api.validators.validate_string_fields])),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='api_person_name_403081_idx')],
            },
        ),
    ]
