# Generated by Django 4.2.5 on 2023-09-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_person_dynamic_attibutes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='dynamic_attibutes',
            new_name='dynamic_attributes',
        ),
    ]
