# Generated by Django 4.2.5 on 2023-09-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_person_dynamic_attibutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dynamic_attibutes',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
