# Generated by Django 4.2.5 on 2023-09-12 18:40

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[api.validators.validate_string_fields]),
        ),
    ]
